name: Build and Push Voice and Video Workers

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  # --- JOB 1: Build the Voice Worker (with HF Token) ---
  build_voice_worker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push voice_worker
        uses: docker/build-push-action@v5
        with:
          context: ./voice_worker
          file: ./voice_worker/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/voice-worker:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          # --- THIS IS THE KEY CHANGE ---
          # This 'secrets' block passes your GitHub Secret named HF_TOKEN
          # to the Dockerfile's secret mount point named 'huggingface_token'.
          secrets: |
            "huggingface_token=${{ secrets.HF_TOKEN }}"

  # --- JOB 2: Build the Video Worker (no change needed) ---
  build_video_worker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push video_worker
        uses: docker/build-push-action@v5
        with:
          context: ./video_worker
          file: ./video_worker/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/video-worker:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          
