# This name will appear in the "Actions" tab of your GitHub repository.
name: Build and Push Voice and Video Workers

# This workflow runs automatically on a push to the 'main' branch.
on:
  push:
    branches: [ "main" ]
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab.

jobs:
  # --- JOB 1: Build the Voice Worker ---
  build_voice_worker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          # This line requires a secret named DOCKERHUB_USERNAME
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          # This line requires a secret named DOCKERHUB_TOKEN
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push voice_worker
        uses: docker/build-push-action@v5
        with:
          context: ./voice_worker
          file: ./voice_worker/Dockerfile
          push: true
          # This line ALSO requires the DOCKERHUB_USERNAME secret to create the tag
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/voice-worker:latest

  # --- JOB 2: Build the Video Worker ---
  build_video_worker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push video_worker
        uses: docker/build-push-action@v5
        with:
          context: ./video_worker
          file: ./video_worker/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/video-worker:latest
          
