name: Build and Push Voice and Video Workers

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  DOCKERHUB_USER: ${{ vars.DOCKERHUB_USER }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

jobs:
  build_voice_worker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push voice_worker
        uses: docker/build-push-action@v5
        with:
          context: ./voice_worker
          file: ./voice_worker/Dockerfile
          push: true
          tags: ${{ vars.DOCKERHUB_USER }}/voice_worker:latest

  build_video_worker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push video_worker
        uses: docker/build-push-action@v5
        with:
          context: ./video_worker
          file: ./video_worker/Dockerfile
          push: true
          tags: ${{ vars.DOCKERHUB_USER }}/video_worker:latest
